-- Purpose: Database schema and table creation script.
CREATE DATABASE IF NOT EXISTS IDentifyDB;
USE IDentifyDB;

CREATE TABLE IF NOT EXISTS STUDENTS (
    full_name VARCHAR(100) NOT NULL,
    Reg_No VARCHAR(20) NOT NULL PRIMARY KEY,
    college_id INT NOT NULL,
    course_id INT NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (college_id) REFERENCES COLLEGES(college_id),
    FOREIGN KEY (course_id) REFERENCES COURSES(course_id)
);

CREATE TABLE IF NOT EXISTS OFFICERS(
    full_name VARCHAR(100) NOT NULL,
    work_id VARCHAR(20) NOT NULL PRIMARY KEY,
    phone_number VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS INVENTORY_RECORDS (
    record_id INT AUTO_INCREMENT PRIMARY KEY,
    Reg_No VARCHAR(20) NOT NULL,
    pickup_point VARCHAR(100) NOT NULL,
    status ENUM('In Storage', 'Handed Over') NOT NULL,
    date_logged TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Reg_No) REFERENCES STUDENTS(Reg_No) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COLLEGES (
    college_id INT AUTO_INCREMENT PRIMARY KEY,
    college_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS COURSES (
    course_id INT AUTO_INCREMENT PRIMARY KEY,
    course_name VARCHAR(100) NOT NULL UNIQUE
);